# Generated by Django 3.0.7 on 2020-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=30)),
                ('male', models.CharField(max_length=6)),
                ('regtime', models.DateTimeField(max_length=6)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
