# Generated by Django 3.0.7 on 2020-08-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_auto_20200806_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
