# Generated by Django 3.0.7 on 2020-08-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_auto_20200806_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=30)),
                ('username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='user_manage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=30)),
                ('username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='user_manage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='user_manage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Leapcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leapcard', models.CharField(max_length=30)),
                ('username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='user_manage.User')),
            ],
        ),
    ]
