# Generated by Django 3.0.7 on 2020-08-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_auto_20200809_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place',
            field=models.CharField(max_length=300),
        ),
    ]
